### PR TITLE
Initial Raven/Sentry Support

### PR DESCRIPTION
**Pull request by qodeboy**
Hello,

This adds basic Raven/Sentry support to this package using [raven/raven](https://github.com/getsentry/raven-php) implementation.

Please review and merge if looks good.

### CODE REVIEW

**Comment by tylercd100** [comment]
Awesome! When I get in to work in about an hour I'll merge this.

**Comment by tylercd100** [comment]
@qodeboy Included in [1.6.0](https://github.com/tylercd100/laravel-notify/releases) also note that I moved raven/raven to a [suggested package instead of a required package](https://github.com/tylercd100/laravel-notify/commit/6f4b389bddac4dee5a9ab5d619f89629988a95a9)

**Comment by tylercd100** [comment]
Also, Thanks for contributing :)

**Comment by qodeboy** [comment]
Cool! Thanks for quick turnaround and great package :)

**Pull request merged**
